version: '4.0'
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src:/app/src'
      - '/app/node_modules'
    ports:
      - 5173:5173
    tty: true
    stdin_open: true
